package coop.bancocredicoop.guv.loader.models;

public enum EstadoCheque {
    INGRESADO, VALIDAR_CMC7, CORREGIDO, OBSERVADO, BALANCEADO, DIF_A_PRESENTAR, EN_PROCESO, DERIVADO_FILIAL, VERIF_DERIVADO_FIL, PRESENTADO, ELIMINADO, ELIMINADO_DUP,
    RESCATADO, RECHAZADO, ACEPTADO, RECIBIDO, PAGADO, DIFERIDO_BALANCEADO;
}
